openapi: 3.0.0
info:
  version: 1.0.0
  title: Zoro Cart API
  termsOfService: 'https://zoro.com/terms/'
  contact:
    email: contact@zoro.com
    url: 'http://zoro.com/contact'
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
  x-logo:
    url: 'https://www.zoro.com/static/cms/img/logos/zoro-logo-color-one-line-dot-com-high-res.png'
  description:
    $ref: info-description.md
servers:
  - url: /v1
tags:
  - name: cart
    description: |-
        The cart represents a user shopping cart carrying the items. The cart can contain zero or many items.
        A cart that is not empty can be checked out for fulfillment.
  - name: catalog
    description: |-
        The catalog represents the catalog of products in the Zoro catalog that can be ordered and shipped. The catalog
        is tiered into 3 layers to enable drilldown and search based on product categories.
x-tagGroups:
  - name: Buy Services
    tags:
      - cart
  - name: Search Services
    tags:
      - catalog
  
paths:
  /cart/health:
    $ref: paths/cart_health.yaml
  /cart:
    $ref: paths/cart.yaml
  /cart/{cartId}:
    $ref: paths/cart_{cartId}.yaml
  /cart/{cartId}/merge:
    $ref: paths/cart_{cartId}_merge.yaml
  /cart/{cartId}/items:
    $ref: paths/cart_{cartId}_items.yaml
  /cart/{cartId}/submitorder:
    $ref: paths/cart_{cartId}_submitorder.yaml
  /cart/{cartId}/items/{zoroNo}:
    $ref: paths/cart_{cartId}_items_{zoroNo}.yaml
  /cart/{cartId}/shippingaddress:
    $ref: paths/cart_{cartId}_shippingaddress.yaml
  /cart/{cartId}/billingaddress:
    $ref: paths/cart_{cartId}_billingaddress.yaml
  /cart/{cartId}/shippingmethod:
    $ref: paths/cart_{cartId}_shippingmethod.yaml
  /cart/clearcache:
    $ref: paths/cart_clearcache.yaml
  /cart/{cartId}/promo:
    $ref: paths/cart_{cartId}_promo.yaml
components:
  securitySchemes:
    oktaJwt:
      type: http
      scheme: bearer
      bearerFormat: JWT
      x-bearerInfoFunc: cart_service.api.auth.verify
